***NumPy - Numerical Python***

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [ ]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.002204186999999802


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00042786099999991833


Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# shape : will gives you the number of rows and columns
a.shape

(4,)

In [ ]:
# creating a 2 dimension array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
# dtype parameter uses to specify the data type of that array
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

initial placeholder means the initial values present in that particular numpy array

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.68489392 0.25352763 0.5164079  0.5846446 ]
 [0.19119214 0.70512175 0.70097858 0.8374312 ]
 [0.23455987 0.2631089  0.25602684 0.00590504]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[94 97 81 94 41]
 [86 14 96 50 77]
 [61 87 91 55 93]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[23 10 82 52 67]
 [28 24 63 47 58]
 [85 12 25 33 52]
 [57 86 84 71 16]
 [34 41 14 78 66]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[2 3 4]
 [1 0 1]
 [9 7 3]]
[[10 13 10]
 [16 19 10]
 [10 19 17]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[12 16 14]
 [17 19 11]
 [19 26 20]]
[[ -8 -10  -6]
 [-15 -19  -9]
 [ -1 -12 -14]]
[[ 20  39  40]
 [ 16   0  10]
 [ 90 133  51]]
[[0.2        0.23076923 0.4       ]
 [0.0625     0.         0.1       ]
 [0.9        0.36842105 0.17647059]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[1 1 3]
 [6 4 3]
 [1 5 7]]
[[13 10 18]
 [14 11 13]
 [11 16 16]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 11 21]
 [20 15 16]
 [12 21 23]]
[[-12  -9 -15]
 [ -8  -7 -10]
 [-10 -11  -9]]
[[ 13  10  54]
 [ 84  44  39]
 [ 11  80 112]]
[[0.07692308 0.1        0.16666667]
 [0.42857143 0.36363636 0.23076923]
 [0.09090909 0.3125     0.4375    ]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 2 4]
 [0 2 0]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 0]
 [2 2]
 [4 0]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 5 9]
 [8 2 3]]
(2, 3)


In [ ]:
# transpose other method
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 8]
 [5 2]
 [9 3]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 2 2]
 [4 6 4]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 2]
 [2 4]
 [6 4]]
(3, 2)


In [ ]:
c = a.reshape(6)
print(c)
print(c.shape)

[8 2 2 4 6 4]
(6,)


In [ ]:
d = a.reshape((1,2,3))
print(d)
print(d.shape)

[[[8 2 2]
  [4 6 4]]]
(1, 2, 3)
